{
 "title": "HTML Kafka Ingestor Pipeline",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "DB Insert Duration (seconds)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "db_insert_duration_seconds_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rows Failed Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rows_failed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Rows Ingested Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rows_ingested_total", "legendFormat": "__auto" }
   ]
  }
 ]
}